# Generated by Django 6.0.3 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nandi', '0002_receipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.TextField(max_length=500),
        ),
    ]
